- name: Install Nginx on App Servers
  become: yes
  hosts: app_servers
  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        state: present
    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes